/**
 * Minimal WASI Python host demonstrating PyOnceLock crash.
 *
 * This program embeds Python and loads a PyO3 extension that uses PyOnceLock.
 * On WASI, the PyOnceLock initialization causes a crash due to missing
 * threading primitives.
 */

#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <stdio.h>
#include <stdlib.h>

// Declaration of the PyO3 extension's init function
// This is generated by PyO3 with the name PyInit_<module_name>
extern PyObject* PyInit_pyoncelock_demo(void);

int main(int argc, char** argv) {
    (void)argc;
    (void)argv;

    fprintf(stderr, "[C] Starting PyOnceLock WASI demo\n");
    fprintf(stderr, "[C] This demonstrates the crash caused by PyOnceLock on WASI\n");
    fprintf(stderr, "[C] ============================================\n\n");

    // Register the extension module BEFORE Python initialization
    // This is required on WASI because dlopen is not available
    fprintf(stderr, "[C] Registering pyoncelock_demo extension...\n");
    if (PyImport_AppendInittab("pyoncelock_demo", PyInit_pyoncelock_demo) == -1) {
        fprintf(stderr, "[C] ERROR: Failed to register pyoncelock_demo\n");
        return 1;
    }
    fprintf(stderr, "[C] Extension registered successfully\n\n");

    // Pre-configure Python for UTF-8 mode
    fprintf(stderr, "[C] Pre-initializing Python...\n");
    PyPreConfig preconfig;
    PyPreConfig_InitIsolatedConfig(&preconfig);
    preconfig.utf8_mode = 1;

    PyStatus status = Py_PreInitialize(&preconfig);
    if (PyStatus_Exception(status)) {
        fprintf(stderr, "[C] ERROR: Python pre-initialization failed\n");
        return 1;
    }
    fprintf(stderr, "[C] Python pre-initialized\n\n");

    // Initialize Python interpreter
    fprintf(stderr, "[C] Initializing Python interpreter...\n");
    Py_Initialize();

    if (!Py_IsInitialized()) {
        fprintf(stderr, "[C] ERROR: Python initialization failed\n");
        return 1;
    }
    fprintf(stderr, "[C] Python interpreter initialized\n\n");

    // Test 1: Simple function (should work)
    fprintf(stderr, "[C] ============================================\n");
    fprintf(stderr, "[C] TEST 1: Import module and call simple_add()\n");
    fprintf(stderr, "[C] This does NOT use any OnceLock and should work\n");
    fprintf(stderr, "[C] ============================================\n\n");

    const char* test1_code =
        "print('[Python] Importing pyoncelock_demo...')\n"
        "import pyoncelock_demo\n"
        "print('[Python] Module imported successfully')\n"
        "print('[Python] Calling simple_add(2, 3)...')\n"
        "result = pyoncelock_demo.simple_add(2, 3)\n"
        "print(f'[Python] Result: {result}')\n"
        "print('[Python] TEST 1 PASSED')\n";

    fprintf(stderr, "[C] Running Python code...\n\n");
    if (PyRun_SimpleString(test1_code) != 0) {
        fprintf(stderr, "\n[C] ERROR: Test 1 failed\n");
        PyErr_Print();
        Py_Finalize();
        return 1;
    }

    // Test 2: std::sync::OnceLock (may crash on WASI)
    fprintf(stderr, "\n[C] ============================================\n");
    fprintf(stderr, "[C] TEST 2: Call test_std_oncelock()\n");
    fprintf(stderr, "[C] This uses std::sync::OnceLock\n");
    fprintf(stderr, "[C] ============================================\n\n");

    const char* test2_code =
        "print('[Python] Calling test_std_oncelock()...')\n"
        "result = pyoncelock_demo.test_std_oncelock()\n"
        "print(f'[Python] Result: {result}')\n"
        "print('[Python] TEST 2 PASSED - std::sync::OnceLock worked!')\n";

    fprintf(stderr, "[C] Running Python code...\n\n");
    if (PyRun_SimpleString(test2_code) != 0) {
        fprintf(stderr, "\n[C] ERROR: Test 2 failed\n");
        PyErr_Print();
        Py_Finalize();
        return 1;
    }

    // Test 3: pyo3::sync::PyOnceLock (may crash on WASI)
    fprintf(stderr, "\n[C] ============================================\n");
    fprintf(stderr, "[C] TEST 3: Call test_py_oncelock()\n");
    fprintf(stderr, "[C] This uses pyo3::sync::PyOnceLock\n");
    fprintf(stderr, "[C] ============================================\n\n");

    const char* test3_code =
        "print('[Python] Calling test_py_oncelock()...')\n"
        "cached_type = pyoncelock_demo.test_py_oncelock()\n"
        "print(f'[Python] Cached type: {cached_type}')\n"
        "print('[Python] TEST 3 PASSED - pyo3::sync::PyOnceLock worked!')\n";

    fprintf(stderr, "[C] Running Python code...\n\n");
    if (PyRun_SimpleString(test3_code) != 0) {
        fprintf(stderr, "\n[C] ERROR: Test 3 failed\n");
        PyErr_Print();
        Py_Finalize();
        return 1;
    }

    fprintf(stderr, "\n[C] ============================================\n");
    fprintf(stderr, "[C] ALL TESTS PASSED\n");
    fprintf(stderr, "[C] ============================================\n");

    Py_Finalize();
    return 0;
}
